### PR TITLE
Prevent Object prototype pollution.

### LINKED ISSUE #39: Fix prototype pollution vulnerability
According to https://hackerone.com/reports/311333, deep-extend is vulnerable to prototype pollution attacks. The vulnerability exists in the utility function where the prototype of `Object` can be overwritten to add or modify existing property on all objects.
Could you fix this as deep-extend is used in other packages such as https://github.com/dominictarr/rc
Thank you.

### PR DESCRIPTION
**Pull request by mwakerman**
See https://hackerone.com/reports/311333.

Resolves #39

### CODE REVIEW

**Comment by mwakerman** [comment]
@gustavobeavis done (I think)

**Comment by unclechu** [comment]
@mwakerman Thanks, I'll make a release soon.

**Comment by unclechu** [comment]
Merged to `dev` branch, closing this.

**Comment by husseinbob** [comment]
> Vulnerability alert still pops up with 0.5.1 @Pablodotnet 

is this an erroneous alert or is the package still vulnerable?

**Comment by unclechu** [comment]
I don't think so, at least I don't have any proofs that it happens.
There is a test for that: https://github.com/unclechu/node-deep-extend/blob/f3f2b4f30fffe8abc9a99a7d6469fb354ca206e9/test/index.spec.js#L260-L266

**Pull request closed without merging**
