### PR TITLE
Error object is cloned as empty

### PR DESCRIPTION
**Pull request by vogdb**
``` js
var deepExtend = require('deep-extend');

var a = {exceptionNormal: new Error('normal')};
deepExtend(a, {exceptionBroken: new Error('broken')});

console.log(a);
```

gives

```
{ exceptionNormal: 
   Error: normal
       at Object.<anonymous> (....)
  exceptionBroken: {} }
```

### CODE REVIEW

**Comment by vogdb** [comment]
@unclechu please review

**Comment by unclechu** [comment]
@vogdb I'm not sure about just copying pointer to error, I guess we should clone it somehow, like we do it with other objects (Data, Buffer, RegExp), am I right?

**Comment by unclechu** [comment]
I guess it's time to new version with use-cases customization, where it's possible to choose some strategies to extend specific objects.

**Comment by unclechu** [comment]
@vogdb Anyway, if we want it right now (about exceptions) then we need to think how to clone exception.

**Comment by vogdb** [comment]
Ah, ok. I didn't think it carefully. Just made it in a workflow rush. Let me think about cloning exception.

**Comment by vogdb** [comment]
@unclechu do you have thoughts about cloning stacks, e.g. `error.stack`? I'm out of ideas, need to sleep.

**Comment by vogdb** [comment]
please look btw

**Comment by unclechu** [comment]
@vogdb Also I think that cloning exceptions making less sense, because it will be new object, that can't be checked easily by `instanceof` operator for example. [This way of cloning](https://github.com/unclechu/node-deep-extend/pull/26/commits/7899769fb4638b41ef52dab8e9c06cde6439f789#diff-5202fc56f6565a0319e4cbad698a7255R59) doesn't consider if exception constructor inherited from `Error` and then another constructor inherited from that one, and now we trying to clone exception just ignoring this levels of inheritance. Cloning objects with exceptions by my opinion is very custom and specific case, and I guess `deep-extend` should have customizable API for that cases, but it would be only in next release, I see no way to implement this without brake backward compatibility.

**Comment by vogdb** [comment]
Ok. Good to know. Closing this for now.

**Pull request closed without merging**
